language: android
#jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26

before_script:
- echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
- chmod +x gradlew

script:
- "./gradlew clean connectedAndroidTest --stacktrace"
- "./gradlew assembleRelease"

notifications:
  email: true