language: android
#jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26

script:
- "./gradlew assembleRelease"
- "./gradlew build jacocoTestReport"

notifications:
  email: true

after_success:
- "./gradlew jacocoTestReport coveralls"